### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by rabidkoala25** [EagleEye2010/VSA-RPG#1]
readme should read

### Join the google chat for more information.

To use, just download this. To download, just click the green "code" button, and then download as zip. Extract or unzip, then open with the Unity Hub. (Click "add" and then select the folder with this project)

If you have added your additions, reach to me, and I will add it to the main project.

Sorry I'm just a stickler for grammar... The mistake was a missing i in "additions."

**Comment by EagleEye2010** [comment]
Good catch, thanks!
